// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package user_db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Session struct {
	ID        string
	UserID    string
	UserAgent string
	IpAddress string
	ExpiresAt pgtype.Timestamp
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
}

type User struct {
	ID          string
	AvatarUrl   string
	Name        string
	Username    string
	Email       string
	Password    string
	PhoneNumber pgtype.Text
	CreatedAt   pgtype.Timestamp
	UpdatedAt   pgtype.Timestamp
}
